CREATE TABLE ORDER_LIST(
	BUYER_SEQ NUMBER(8)
	PRODUCT_SEQ NUMBER
	ORDER_SORT NUMBER
	ORDER_DATE DATE
	ORDER_SUPPLY NUMBER
	ORDER_TAX_VALUE NUMBER
	ORDER_COLLECT_MONEY NUMBER
	ORDER_NOT_COLLECT_MONEY NUMBER
	ORDER_TOTAL NUMBER
	ORDER_COUNT NUMBER
	ORDER_NUM NUMBER
)

SELECT * FROM ORDER_LIST;

select to_char(systimestamp, 'YYYYMMDDHHMISS') from TEST;

select ORDER_NUM((to_char(systimestamp, 'YYYYMMDDHHMISSFF'))/1000) FROM ORDER_LIST;

SELECT * FROM PRODUCT_UNIT_CATE;

ALTER TABLE ORDER_LIST ADD (ORDER_STANDARD VARCHAR2());



 SELECT O.BUYER_SEQ, O.ORDER_SORT, O.ORDER_DATE, O.ORDER_SUPPLY_PRICE, O.ORDER_TAX_VALUE, 
 O.ORDER_COLLECT_MONEY, O.ORDER_NOT_COLLECT_MONEY, O.ORDER_TOTAL, 
 O.PRODUCT_SEQ, O.ORDER_COUNT, O.ORDER_NUM, P.PRODUCT_NAME,O.ORDER_DEL, P.PRODUCT_STANDARD
FROM ORDER_LIST O, PRODUCT P
 WHERE O.PRODUCT_SEQ = P.PRODUCT_SEQ 
 AND O.ORDER_NUM = '20200812023550451' AND O.BUYER_SEQ = 5
 GROUP BY ; 
 
 SELECT O.BUYER_SEQ, O.ORDER_DATE,
 O.ORDER_SUPPLY_PRICE,
 O.ORDER_TAX_VALUE, 
O.ORDER_COLLECT_MONEY,
 O.ORDER_NOT_COLLECT_MONEY, 
 O.ORDER_TOTAL,
 O.PRODUCT_SEQ, 
O.ORDER_COUNT, 
O.ORDER_NUM,
 P.PRODUCT_NAME,
 O.ORDER_DEL,
 P.PRODUCT_STANDARD, 
 P.PRODUCT_TRADE_PRICE,
P.PRODUCT_UNIT,
 U.PRODUCT_UNIT 
FROM ORDER_LIST O, PRODUCT P, PRODUCT_UNIT_CATE U 
 WHERE O.PRODUCT_SEQ = P.PRODUCT_SEQ
 AND P.PRODUCT_UNIT = U.SEQ_NUM 
 AND O.ORDER_NUM = '20200812023740128' AND O.BUYER_SEQ = 5 AND O.ORDER_DEL=0;
 
 
SELECT COUNT(O.ORDER_DATE)
FROM ORDER_LIST O, BUYER B
WHERE O.BUYER_SEQ = B.BUYER_SEQ
AND B.SELLER_ID = 'test1'
AND O.ORDER_NUM = '20200812023550451';
 
 
 
 