--PRODUCT TABLE 에 SELLER_ID 를 넣어주는 쿼리문
ALTER TABLE PRODUCT
    ADD (SELLER_ID VARCHAR2(50));
ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_SELLERID FOREIGN KEY(SELLER_ID)
    REFERENCES SELLER (SELLER_ID);