CREATE TABLE PRODUCT
(
    PRODUCT_SEQ            NUMBER(8)      NOT NULL, 
    PRODUCT_NAME           VARCHAR2(20)   NOT NULL, 
    PRODUCT_UNIT           NUMBER(2)      NOT NULL, 
    PRODUCT_TRADE_PRICE    NUMBER      NOT NULL, 
    PRODUCT_SORT           VARCHAR2(10)    NOT NULL, 
    PRODUCT_PIECE_BOX      NUMBER(5)      NOT NULL, 
    PRODUCT_STANDARD       VARCHAR2(20)    NOT NULL, 
    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_SEQ)
)
/

CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1;
/


COMMENT ON TABLE PRODUCT IS '상품정보'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_SEQ IS 'SEQ'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품명'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_UNIT IS '단위'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_TRADE_PRICE IS '도매가'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_SORT IS '품목구분'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_PIECE_BOX IS '박스당낱개'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_STANDARD IS '상품규격'
/
ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_PRODUCT_SORT_PRODUC FOREIGN KEY (PRODUCT_SORT)
        REFERENCES PRODUCT_SORT (PRODUCT_SORT)
/

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_PRODUCT_STANDARD_PR FOREIGN KEY (PRODUCT_STANDARD)
        REFERENCES PRODUCT_STANDARD_CATE (PRODUCT_STANDARD)
/

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_PRODUCT_UNIT_PRODUC FOREIGN KEY (PRODUCT_UNIT)
        REFERENCES PRODUCT_UNIT_CATE (seq_num)
/

CREATE TABLE PRODUCT_SORT
(
    PRODUCT_SORT    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT PRODUCT_SORT_PK PRIMARY KEY (PRODUCT_SORT)
)
/

COMMENT ON TABLE PRODUCT_SORT IS 'Product_품목구분'
/

COMMENT ON COLUMN PRODUCT_SORT.PRODUCT_SORT IS '품목구분'
/

CREATE TABLE PRODUCT_STANDARD_CATE
(
    PRODUCT_STANDARD    VARCHAR2(40)    NOT NULL, 
    CONSTRAINT PRODUCT_STANDARD_CATE_PK PRIMARY KEY (PRODUCT_STANDARD)
)
/

COMMENT ON COLUMN PRODUCT_STANDARD_CATE.PRODUCT_STANDARD IS '상품규격'
/

CREATE TABLE PRODUCT_UNIT_CATE
(
    seq_num         NUMBER          NOT NULL, 
    PRODUCT_UNIT    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT PRODUCT_UNIT_CATE_PK PRIMARY KEY (seq_num)
)
/

COMMENT ON COLUMN PRODUCT_UNIT_CATE.PRODUCT_UNIT IS '단위'
/

CREATE TABLE PRODUCT_COUNT
(
    PRODUCT_SEQ      NUMBER    NOT NULL, 
    PRODUCT_COUNT    NUMBER    NOT NULL, 
    CONSTRAINT PRODUCT_COUNT_PK PRIMARY KEY (PRODUCT_SEQ)
)
/

COMMENT ON TABLE PRODUCT_COUNT IS '재고수량'
/

COMMENT ON COLUMN PRODUCT_COUNT.PRODUCT_SEQ IS '상품번호'
/

COMMENT ON COLUMN PRODUCT_COUNT.PRODUCT_COUNT IS '재고수량'
/

ALTER TABLE PRODUCT_COUNT
    ADD CONSTRAINT FK_PRODUCT_COUNT_PRODUCT_SEQ_P FOREIGN KEY (PRODUCT_SEQ)
        REFERENCES PRODUCT (PRODUCT_SEQ)
/
CREATE TABLE TOTAL
(
    TOTAL_ORDER_NUM    NUMBER    NOT NULL, 
    TOTAL_DATE         DATE      NOT NULL, 
    TOTAL_TOTAL        NUMBER    NOT NULL
)
/

COMMENT ON TABLE TOTAL IS '누계'
/

COMMENT ON COLUMN TOTAL.TOTAL_ORDER_NUM IS '주문번호'
/

COMMENT ON COLUMN TOTAL.TOTAL_DATE IS '날짜'
/

COMMENT ON COLUMN TOTAL.TOTAL_TOTAL IS '총누계'
/

commit;

--product productunitcate product standardcate product_sort table product_count totoal_table
